更新機能の追加
s1f10220089/djando-test-exercise pull request #6
Opened 2023-07-13 03:14 UTC by s1F102200862

2023-07-14 01:16 UTC, s1f10220089 approved these changes
プルリクエストを承認

2023-07-19 12:20 UTC, s1f10220089 approved these changes
承認します

2023-07-19 12:20 UTC, s1f10220089 approved these changes

2023-07-19 12:34 UTC, s1f10220089 requested changes
コンフリクトを修正してください

2023-07-20 01:47 UTC, s1f10220089 reviewed
修正の確認

2023-07-20 02:33 UTC, konjikun commented
mainブランチをpullしてから文法のエラーを修正してください。
git add .使っておけば比較で自分の書いたコード残して修正も出来ます。

2023-07-23 13:18 UTC, s1F102200862 commented
すべての✅は通っているので、コンフリクト解消できたとおもうのですが、
自分のところでの表示はマージできなくなってるんですけど、ＰＭさんマージできるのでしょうか。。。

2023-07-23 17:52 UTC, s1f10220089 approved these changes
承認

2023-07-23 17:52 UTC, merged